#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building the project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Bad styling
    Prettier Check Failed. Run "npm run format", add changes, and try commit again.';
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check.
    Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'Passed style and type test.'

# If everything passes... Now we can commit
echo '✅✅✅✅ Committing ✅✅✅✅'